package org.rapharino.web.base.admin.dao;

import java.util.List;
import org.rapharino.web.base.admin.model.Icon;

public interface IconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_icon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_icon
     *
     * @mbg.generated
     */
    int insert(Icon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_icon
     *
     * @mbg.generated
     */
    Icon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_icon
     *
     * @mbg.generated
     */
    List<Icon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_icon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Icon record);
}