package org.rapharino.web.base.admin.dao;

import java.util.List;
import org.rapharino.web.base.admin.model.Organization;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_organization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_organization
     *
     * @mbg.generated
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_organization
     *
     * @mbg.generated
     */
    Organization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_organization
     *
     * @mbg.generated
     */
    List<Organization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Organization record);
}