package org.rapharino.web.base.admin.dao;

import java.util.List;
import org.rapharino.web.base.admin.model.Resource;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource
     *
     * @mbg.generated
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource
     *
     * @mbg.generated
     */
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource
     *
     * @mbg.generated
     */
    List<Resource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Resource record);
}