package org.rapharino.web.base.admin.model;

/**
 * Generated by Rapharino.
 * 
 * 表名: tb_resource
 */
public class Resource {
    /**
     * 
     * 表字段: tb_resource.id
     */
    private Integer id;

    /**
     * 
     * 表字段: tb_resource.name
     */
    private String name;

    /**
     * 
     * 表字段: tb_resource.type
     */
    private String type;

    /**
     * 
     * 表字段: tb_resource.url
     */
    private String url;

    /**
     * 
     * 表字段: tb_resource.parent_id
     */
    private Integer parentId;

    /**
     * 
     * 表字段: tb_resource.parent_ids
     */
    private String parentIds;

    /**
     * 
     * 表字段: tb_resource.permission
     */
    private String permission;

    /**
     * 
     * 表字段: tb_resource.available
     */
    private Byte available;

    /**
     * 
     * 表字段: tb_resource.icon
     */
    private Integer icon;

    /**
     * This method returns the value of the database column tb_resource.id
     * @return the value of tb_resource.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the value of the database column tb_resource.id
     * @param id the value for tb_resource.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column tb_resource.name
     * @return the value of tb_resource.name
     */
    public String getName() {
        return name;
    }

    /**
     * This method sets the value of the database column tb_resource.name
     * @param name the value for tb_resource.name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method returns the value of the database column tb_resource.type
     * @return the value of tb_resource.type
     */
    public String getType() {
        return type;
    }

    /**
     * This method sets the value of the database column tb_resource.type
     * @param type the value for tb_resource.type
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method returns the value of the database column tb_resource.url
     * @return the value of tb_resource.url
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method sets the value of the database column tb_resource.url
     * @param url the value for tb_resource.url
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method returns the value of the database column tb_resource.parent_id
     * @return the value of tb_resource.parent_id
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method sets the value of the database column tb_resource.parent_id
     * @param parentId the value for tb_resource.parent_id
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method returns the value of the database column tb_resource.parent_ids
     * @return the value of tb_resource.parent_ids
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method sets the value of the database column tb_resource.parent_ids
     * @param parentIds the value for tb_resource.parent_ids
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method returns the value of the database column tb_resource.permission
     * @return the value of tb_resource.permission
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method sets the value of the database column tb_resource.permission
     * @param permission the value for tb_resource.permission
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method returns the value of the database column tb_resource.available
     * @return the value of tb_resource.available
     */
    public Byte getAvailable() {
        return available;
    }

    /**
     * This method sets the value of the database column tb_resource.available
     * @param available the value for tb_resource.available
     */
    public void setAvailable(Byte available) {
        this.available = available;
    }

    /**
     * This method returns the value of the database column tb_resource.icon
     * @return the value of tb_resource.icon
     */
    public Integer getIcon() {
        return icon;
    }

    /**
     * This method sets the value of the database column tb_resource.icon
     * @param icon the value for tb_resource.icon
     */
    public void setIcon(Integer icon) {
        this.icon = icon;
    }
}