package org.rapharino.web.base.admin.model;

/**
 * Generated by Rapharino.
 * 
 * 表名: tb_role
 */
public class Role {
    /**
     * 
     * 表字段: tb_role.id
     */
    private Integer id;

    /**
     * 
     * 表字段: tb_role.name
     */
    private String name;

    /**
     * 
     * 表字段: tb_role.description
     */
    private String description;

    /**
     * 
     * 表字段: tb_role.resourceIds
     */
    private String resourceids;

    /**
     * 
     * 表字段: tb_role.available
     */
    private Byte available;

    /**
     * This method returns the value of the database column tb_role.id
     * @return the value of tb_role.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the value of the database column tb_role.id
     * @param id the value for tb_role.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column tb_role.name
     * @return the value of tb_role.name
     */
    public String getName() {
        return name;
    }

    /**
     * This method sets the value of the database column tb_role.name
     * @param name the value for tb_role.name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method returns the value of the database column tb_role.description
     * @return the value of tb_role.description
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method sets the value of the database column tb_role.description
     * @param description the value for tb_role.description
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method returns the value of the database column tb_role.resourceIds
     * @return the value of tb_role.resourceIds
     */
    public String getResourceids() {
        return resourceids;
    }

    /**
     * This method sets the value of the database column tb_role.resourceIds
     * @param resourceids the value for tb_role.resourceIds
     */
    public void setResourceids(String resourceids) {
        this.resourceids = resourceids == null ? null : resourceids.trim();
    }

    /**
     * This method returns the value of the database column tb_role.available
     * @return the value of tb_role.available
     */
    public Byte getAvailable() {
        return available;
    }

    /**
     * This method sets the value of the database column tb_role.available
     * @param available the value for tb_role.available
     */
    public void setAvailable(Byte available) {
        this.available = available;
    }
}